-- supabase/seed/004_season_award_winners.sql
-- W.5 Inc 3 Wave B1 - the three weekly-score-derived season awards (#4 The Cannon,
-- #12 The Black Rose, #33 One-Point Club). Generated by scripts/gen_season_award_winners.py
-- in the engine repo - do not hand-edit. Idempotent: DELETE these awards then INSERT.
-- Franchise resolves by (league canonical_id, canonical code) - no hardcoded UUIDs.
-- Prerequisite: migration 028 (season_award_winners) applied. Paste-safe (no in-comment semicolons).
BEGIN;
DELETE FROM season_award_winners WHERE league_id = (SELECT id FROM leagues WHERE canonical_id = '70985') AND award_id IN ('4', '12', '33');
INSERT INTO season_award_winners (league_id, award_id, season, franchise_id, value, detail, provenance)
SELECT l.id, v.award_id, v.season, v.franchise_id, v.value, v.detail::jsonb, 'engine:matchup-derived'
FROM (VALUES
  ('12', 2010, '0006', 142.0, '{"opponent": "0008", "week": 10}'),
  ('12', 2011, '0010', 149.5, '{"opponent": "0004", "week": 2}'),
  ('12', 2012, '0006', 137.5, '{"opponent": "0009", "week": 8}'),
  ('12', 2013, '0003', 127.0, '{"opponent": "0010", "week": 1}'),
  ('12', 2014, '0007', 136.5, '{"opponent": "0009", "week": 10}'),
  ('12', 2015, '0006', 121.5, '{"opponent": "0004", "week": 3}'),
  ('12', 2016, '0005', 125.0, '{"opponent": "0004", "week": 9}'),
  ('12', 2017, '0006', 134.4, '{"opponent": "0001", "week": 7}'),
  ('12', 2018, '0009', 135.95, '{"opponent": "0008", "week": 1}'),
  ('12', 2019, '0009', 174.5, '{"opponent": "0010", "week": 5}'),
  ('12', 2020, '0005', 135.95, '{"opponent": "0001", "week": 12}'),
  ('12', 2021, '0003', 144.1, '{"opponent": "0002", "week": 5}'),
  ('12', 2022, '0005', 141.7, '{"opponent": "0003", "week": 8}'),
  ('12', 2023, '0006', 150.55, '{"opponent": "0004", "week": 10}'),
  ('12', 2024, '0003', 163.5, '{"opponent": "0002", "week": 14}'),
  ('12', 2025, '0009', 147.3, '{"opponent": "0008", "week": 4}'),
  ('33', 2013, '0009', 1.0, '{"runner_up": "0010", "week": 16}'),
  ('33', 2019, '0002', 1.45, '{"runner_up": "0005", "week": 16}'),
  ('4', 2010, '0009', 170.0, '{"opponent": "0008", "week": 1}'),
  ('4', 2011, '0010', 169.0, '{"opponent": "0001", "week": 4}'),
  ('4', 2012, '0001', 183.5, '{"opponent": "0008", "week": 9}'),
  ('4', 2013, '0010', 166.5, '{"opponent": "0007", "week": 15}'),
  ('4', 2014, '0001', 187.5, '{"opponent": "0007", "week": 8}'),
  ('4', 2015, '0009', 159.0, '{"opponent": "0010", "week": 1}'),
  ('4', 2016, '0001', 168.0, '{"opponent": "0007", "week": 3}'),
  ('4', 2017, '0005', 156.6, '{"opponent": "0010", "week": 11}'),
  ('4', 2018, '0003', 162.65, '{"opponent": "0004", "week": 11}'),
  ('4', 2019, '0010', 177.75, '{"opponent": "0008", "week": 8}'),
  ('4', 2020, '0006', 177.7, '{"opponent": "0008", "week": 4}'),
  ('4', 2021, '0004', 162.15, '{"opponent": "0003", "week": 13}'),
  ('4', 2022, '0006', 187.3, '{"opponent": "0010", "week": 9}'),
  ('4', 2023, '0006', 185.05, '{"opponent": "0004", "week": 4}'),
  ('4', 2024, '0002', 198.8, '{"opponent": "0003", "week": 14}'),
  ('4', 2025, '0002', 192.15, '{"opponent": "0005", "week": 7}')
) AS v(award_id, season, franchise_id, value, detail)
JOIN leagues l ON l.canonical_id = '70985';
COMMIT;
