-- 027_franchise_season_records_wave2.sql
-- W.5 Increment 2 Wave 2 - two engine-derived columns on franchise_season_records (008) for the
-- Live Records Group B (the synced championship/season record gains the facts these two plaques read):
--   points_against  - REGULAR-SEASON points allowed per (franchise, season). The Iron Curtain reads
--                     the best all-time points-allowed AVERAGE (min). The regular-season GAME COUNT
--                     for that average is derived from existing columns (wins+losses+ties minus a
--                     championship appearance, result in CHAMPION/RUNNER_UP), so no count column.
--   blowout_wins_60 - count of wins by margin 60 or more over ALL decided games per (franchise,
--                     season). The Executioner reads the all-time sum (max).
--
-- Both are engine-matchup-derived facts (same provenance idiom, provenance stays
-- 'engine:matchup-derived'). ADDITIVE and NULLABLE: existing rows are backfilled in the SAME apply
-- session by a TARGETED UPDATE (generated by scripts/gen_supabase_rebuild.py --backfill in the engine
-- repo), never a destructive re-seed. No RLS change, no new gate.
--
-- FOUNDER-APPLIED via the Supabase SQL editor (Charter section 7). A FRESH prod object-existence
-- probe precedes this apply. Paste-safe: no semicolons inside comments (the 025 lesson).
ALTER TABLE franchise_season_records ADD COLUMN IF NOT EXISTS points_against numeric(8,2);
ALTER TABLE franchise_season_records ADD COLUMN IF NOT EXISTS blowout_wins_60 integer;
